### ISSUE TITLE
Dev User Registration - Administrative Developer

### ISSUE THREAD

**Issue by seobrand** [egortimofeev/genius#5] opened 2015-03-17 19:28 UTC
Accept query string from ClickFunnel and populate the initial signup screen correctly

**Comment by egortimofeev** [comment] 2015-03-18 17:32
Please give more details what I need to accept and where I can get the details about it.

**Comment by egortimofeev** [comment] 2015-03-19 15:14
seems done. waiting on feedback from Jenelle on #7. closing this for now as it is duplicate of #7 in this case.

**Closed by egortimofeev** 2015-03-19 15:14 UTC
Labels: End to End User Registration
